In [1]:
import pandas as pd

In [8]:
web_stats = {'Day':[1,2,3,4,5,6],
             'Visitors':[43,34,65,56,29,76],
             'Bounce Rate':[65,67,78,65,45,52]}

df = pd.DataFrame(web_stats)
df.head()

In [12]:
df = pd.read_excel('employees.xlsx', sheet_name='Sheet1')

In [13]:
df.head()

EMPLOYEE_ID FIRST_NAME LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
0          100     Steven      King     SKING  515.123.4567 1987-06-17   
1          101      Neena   Kochhar  NKOCHHAR  515.123.4568 1989-09-21   
2          102        Lex   De Haan   LDEHAAN  515.123.4569 1993-01-13   
3          103  Alexander    Hunold   AHUNOLD  590.423.4567 1990-01-03   
4          104      Bruce     Ernst    BERNST  590.423.4568 1991-05-21   

    JOB_ID  SALARY  COMMISSION_PCT  MANAGER_ID  DEPARTMENT_ID  
0  AD_PRES   24000             NaN         NaN           90.0  
1    AD_VP   17000             NaN       100.0           90.0  
2    AD_VP   17000             NaN       100.0           90.0  
3  IT_PROG    9000             NaN       102.0           60.0  
4  IT_PROG    6000             NaN       103.0           60.0

In [14]:
df.columns

Index(['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME', 'EMAIL', 'PHONE_NUMBER',
       'HIRE_DATE', 'JOB_ID', 'SALARY', 'COMMISSION_PCT', 'MANAGER_ID',
       'DEPARTMENT_ID'],
      dtype='object')

In [15]:
df = df.drop("COMMISSION_PCT", axis=1)

In [16]:
df.head()

EMPLOYEE_ID FIRST_NAME LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
0          100     Steven      King     SKING  515.123.4567 1987-06-17   
1          101      Neena   Kochhar  NKOCHHAR  515.123.4568 1989-09-21   
2          102        Lex   De Haan   LDEHAAN  515.123.4569 1993-01-13   
3          103  Alexander    Hunold   AHUNOLD  590.423.4567 1990-01-03   
4          104      Bruce     Ernst    BERNST  590.423.4568 1991-05-21   

    JOB_ID  SALARY  MANAGER_ID  DEPARTMENT_ID  
0  AD_PRES   24000         NaN           90.0  
1    AD_VP   17000       100.0           90.0  
2    AD_VP   17000       100.0           90.0  
3  IT_PROG    9000       102.0           60.0  
4  IT_PROG    6000       103.0           60.0

In [17]:
df['FIRST_NAME']

0           Steven
1            Neena
2              Lex
3        Alexander
4            Bruce
5            David
6            Valli
7            Diana
8            Nancy
9           Daniel
10            John
11          Ismael
12     Jose Manuel
13            Luis
14             Den
15       Alexander
16          Shelli
17           Sigal
18             Guy
19           Karen
20         Matthew
21            Adam
22           Payam
23          Shanta
24           Kevin
25           Julia
26           Irene
27           James
28          Steven
29           Laura
          ...     
77            Jack
78       Kimberely
79         Charles
80         Winston
81            Jean
82          Martha
83          Girard
84         Nandita
85          Alexis
86           Julia
87         Anthony
88           Kelly
89        Jennifer
90         Timothy
91         Randall
92           Sarah
93         Britney
94          Samuel
95           Vance
96           Alana
97           Kevin
98          

In [18]:
df.EMAIL

0         SKING
1      NKOCHHAR
2       LDEHAAN
3       AHUNOLD
4        BERNST
5       DAUSTIN
6      VPATABAL
7      DLORENTZ
8      NGREENBE
9       DFAVIET
10        JCHEN
11     ISCIARRA
12      JMURMAN
13        LPOPP
14     DRAPHEAL
15        AKHOO
16       SBAIDA
17      STOBIAS
18      GHIMURO
19     KCOLMENA
20       MWEISS
21       AFRIPP
22     PKAUFLIN
23     SVOLLMAN
24     KMOURGOS
25       JNAYER
26     IMIKKILI
27      JLANDRY
28      SMARKLE
29      LBISSOT
         ...   
77     JLIVINGS
78       KGRANT
79     CJOHNSON
80      WTAYLOR
81      JFLEAUR
82     MSULLIVA
83       GGEONI
84     NSARCHAN
85        ABULL
86     JDELLING
87      ACABRIO
88       KCHUNG
89       JDILLY
90       TGATES
91     RPERKINS
92        SBELL
93     BEVERETT
94      SMCCAIN
95       VJONES
96       AWALSH
97      KFEENEY
98     DOCONNEL
99       DGRANT
100     JWHALEN
101    MHARTSTE
102        PFAY
103     SMAVRIS
104       HBAER
105    SHIGGINS
106      WGIETZ
Name: EMAIL, Length: 107

In [19]:
df[['FIRST_NAME','EMAIL']]

FIRST_NAME     EMAIL
0         Steven     SKING
1          Neena  NKOCHHAR
2            Lex   LDEHAAN
3      Alexander   AHUNOLD
4          Bruce    BERNST
5          David   DAUSTIN
6          Valli  VPATABAL
7          Diana  DLORENTZ
8          Nancy  NGREENBE
9         Daniel   DFAVIET
10          John     JCHEN
11        Ismael  ISCIARRA
12   Jose Manuel   JMURMAN
13          Luis     LPOPP
14           Den  DRAPHEAL
15     Alexander     AKHOO
16        Shelli    SBAIDA
17         Sigal   STOBIAS
18           Guy   GHIMURO
19         Karen  KCOLMENA
20       Matthew    MWEISS
21          Adam    AFRIPP
22         Payam  PKAUFLIN
23        Shanta  SVOLLMAN
24         Kevin  KMOURGOS
25         Julia    JNAYER
26         Irene  IMIKKILI
27         James   JLANDRY
28        Steven   SMARKLE
29         Laura   LBISSOT
..           ...       ...
77          Jack  JLIVINGS
78     Kimberely    KGRANT
79       Charles  CJOHNSON
80       Winston   WTAYLOR
81          Jean   JFLEAUR
82        Martha  MSULLIVA
83        Girard    GGEONI
84       Nandita  NSARCHAN
85        Alexis     ABULL
86         Julia  JDELLING
87       Anthony   ACABRIO
88         Kelly    KCHUNG
89      Jennifer    JDILLY
90       Timothy    TGATES
91       Randall  RPERKINS
92         Sarah     SBELL
93       Britney  BEVERETT
94        Samuel   SMCCAIN
95         Vance    VJONES
96         Alana    AWALSH
97         Kevin   KFEENEY
98        Donald  DOCONNEL
99       Douglas    DGRANT
100     Jennifer   JWHALEN
101      Michael  MHARTSTE
102          Pat      PFAY
103        Susan   SMAVRIS
104      Hermann     HBAER
105      Shelley  SHIGGINS
106      William    WGIETZ

[107 rows x 2 columns]

In [20]:
df.to_csv('employees.csv')

In [24]:
# https://simple.wikipedia.org/wiki/List_of_U.S._states
movie = pd.read_html("https://en.wikipedia.org/wiki/List_of_highest-grossing_films")
print(type(movie))
print(movie)

<class 'list'>
[       0      1                                              2  \
0   Rank   Peak                                          Title   
1      1      1                                         Avatar   
2      2      1                                        Titanic   
3      3      3                   Star Wars: The Force Awakens   
4      4      4                         Avengers: Infinity War   
5      5      3                                 Jurassic World   
6      6      3                                   The Avengers   
7      7      4                                      Furious 7   
8      8      5                        Avengers: Age of Ultron   
9      9      9                                  Black Panther   
10    10      3  Harry Potter and the Deathly Hallows – Part 2   
11    11      9                       Star Wars: The Last Jedi   
12    12     12                 Jurassic World: Fallen Kingdom   
13   13F      5                                         Froz

In [23]:
movie_df = movie[0]
movie_df.columns = movie_df.iloc[0]
movie_df.drop(movie_df.index[[0]] , inplace=True)
movie_df.head(20)

0  Rank Peak                                          Title   Worldwide gross  \
1     1    1                                         Avatar    $2,787,965,087   
2     2    1                                        Titanic    $2,187,463,944   
3     3    3                   Star Wars: The Force Awakens    $2,068,223,624   
4     4    4                         Avengers: Infinity War    $2,046,548,594   
5     5    3                                 Jurassic World    $1,671,713,208   
6     6    3                                   The Avengers    $1,518,812,988   
7     7    4                                      Furious 7    $1,516,045,911   
8     8    5                        Avengers: Age of Ultron    $1,405,403,694   
9     9    9                                  Black Panther    $1,346,904,876   
10   10    3  Harry Potter and the Deathly Hallows – Part 2    $1,341,511,219   
11   11    9                       Star Wars: The Last Jedi    $1,332,539,889   
12   12   12                 Jurassic World: Fallen Kingdom    $1,303,673,615   
13  13F    5                                         Frozen    $1,290,000,000   
14   14   10                           Beauty and the Beast    $1,263,521,126   
15   15   11                        The Fate of the Furious  $1,238,764,765F8   
16   16    5                                     Iron Man 3    $1,214,811,252   
17   17   17                                  Incredibles 2    $1,210,072,582   
18   18   10                                        Minions    $1,159,398,397   
19   19   12                     Captain America: Civil War    $1,153,304,495   
20   20    4                 Transformers: Dark of the Moon    $1,123,794,079   

0   Year  Reference(s)  
1   2009    [# 1][# 2]  
2   1997    [# 3][# 4]  
3   2015    [# 5][# 6]  
4   2018         [# 7]  
5   2015    [# 8][# 9]  
6   2012  [# 10][# 11]  
7   2015  [# 12][# 13]  
8   2015  [# 14][# 13]  
9   2018        [# 15]  
10  2011  [# 16][# 17]  
11  2017  [# 18][# 19]  
12  2018        [# 20]  
13  2013  [# 21][# 22]  
14  2017  [# 23][# 24]  
15  2017  [# 25][# 24]  
16  2013  [# 26][# 27]  
17  2018        [# 28]  
18  2015   [# 29][# 9]  
19  2016  [# 30][# 31]  
20  2011  [# 32][# 17]

In [22]:
df1 = pd.DataFrame({'HPI':[80,85,88,85],
                    'Int_rate':[2, 3, 2, 2],
                    'US_GDP_Thousands':[50, 55, 65, 55]},
                   index = [2001, 2002, 2003, 2004])

df2 = pd.DataFrame({'HPI':[80,85,88,85],
                    'Int_rate':[2, 3, 2, 2],
                    'US_GDP_Thousands':[50, 55, 65, 55]},
                   index = [2005, 2006, 2007, 2008])

df3 = pd.DataFrame({'HPI':[80,85,88,85],
                    'Int_rate':[2, 3, 2, 2],
                    'Low_tier_HPI':[50, 52, 50, 53]},
                   index = [2001, 2002, 2003, 2004])

In [26]:
pd.concat([df1,df2]).head(10)

HPI  Int_rate  US_GDP_Thousands
2001   80         2                50
2002   85         3                55
2003   88         2                65
2004   85         2                55
2005   80         2                50
2006   85         3                55
2007   88         2                65
2008   85         2                55

### numpy


In [13]:
import csv
with open('wines.csv', 'r') as f:
    wines = list(csv.reader(f, delimiter=';'))
print(wines[:3])

[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]


In [14]:
print(wines[:3])

[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]


In [15]:
import numpy as np
wines = np.array(wines[1:], dtype=np.float)
wines

array([[ 7.4   ,  0.7   ,  0.    ,  1.9   ,  0.076 , 11.    , 34.    ,
         0.9978,  3.51  ,  0.56  ,  9.4   ,  5.    ],
       [ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    , 67.    ,
         0.9968,  3.2   ,  0.68  ,  9.8   ,  5.    ]])

In [16]:
wines.shape

(2, 12)

In [17]:
empty_array = np.zeros((3,4))
empty_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.random.rand(3,4)

array([[0.59207555, 0.67708679, 0.91720738, 0.14245642],
       [0.71405735, 0.49494845, 0.57847744, 0.19758399],
       [0.94844793, 0.0918517 , 0.75770375, 0.8963448 ]])

In [37]:
wines = np.genfromtxt("wines.csv", delimiter=";", skip_header=1)

In [38]:
wines[1]

array([ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    , 67.    ,
        0.9968,  3.2   ,  0.68  ,  9.8   ,  5.    ])

### 1-Dimensional NumPy Arrays

In [44]:
third_wine = wines[1,:]

In [45]:
third_wine

array([ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    , 67.    ,
        0.9968,  3.2   ,  0.68  ,  9.8   ,  5.    ])

In [46]:
third_wine[1]

0.88

### N-Dimensional NumPy Arrays

In [47]:
year_one = [
    [500,505,490],
    [810,450,678],
    [234,897,430],
    [560,1023,640]
]

In [48]:
earnings = [
            [
                [500,505,490],
                [810,450,678],
                [234,897,430],
                [560,1023,640]
            ],
            [
                [600,605,490],
                [345,900,1000],
                [780,730,710],
                [670,540,324]
            ]
          ]

In [49]:
earnings = np.array(earnings)
earnings[0,0,0]

500

In [50]:
earnings[0,0,1]

505

In [51]:
earnings.shape

(2, 4, 3)

### Map, filter, Reduce

In [6]:
def add_one(this_item):
    return this_item + 1

In [7]:
numbers = [1,2,3,4,5]
res = map(add_one, numbers)

In [9]:
for i in res:
    print(i)

2
3
4
5
6


In [16]:
def is_even(this_item):
    return this_item % 2 == 0

In [17]:
res = filter(is_even,numbers)

In [18]:
for i in res:
    print(i)

2
4


In [19]:
def add_item(first, second):
    return first + second

In [22]:
from functools import reduce
reduce(add_item, numbers)

15

In [ ]:
# difference between list and tuple
b    = [1,2]   
b[0] = 3       # [3, 2]

a    = (1,2)
a[0] = 3       # Error


a     = (1,2)
b     = [1,2]  

id(a)          # 140230916716520
id(b)          # 748527696

a   += (3,)    # (1, 2, 3)
b   += [3]     # [1, 2, 3]

id(a)          # 140230916878160
id(b)          # 748527696

In [25]:
import dbms
import pandas as pd
con = dbms.connect.oracle("scott", "tiger", "orcl", host="10.188.193.152", port=1521)
cs = con.cursor()
cs.execute('SELECT * FROM ' + "LOCATIONS")

columns = [x[0] for x in cs.description]

pdf = pd.DataFrame(cs.fetchall(), columns=columns)

con.close()

In [26]:
pdf.head()

LOCATION_ID STREET_ADDRESS POSTAL_CODE       CITY STATE_PROVINCE COUNTRY_ID
0        5000      bangalore      560017  marathali            btm         BA
1        5005      bangalore      560018  marathalA           btms         CA
2        5006     bangalore1      560019  marathalb           btml         DA
3        5007     bangalore2      560020  marathalc           btmK         EA
4          50     bangalore3      560014  marathalc           btme         MA